definitions/json/CaseTypeTab.json
package.json
src/test/access-control-transformer.test.js
src/test/convertion.test.js
src/test/json2xlsx.js
src/test/sheet-utils.test.js
src/test/string-utils.test.js
src/test/substitutor.test.js
src/test/xlsx2json.js

Fixed files after a merge seems to have overwritten them.
```
[ ] Yes
[X] No
```

Fixed files after accidental merge

---

.gitignore
definitions/json/CaseEvent.json
definitions/json/CaseTypeTab.json
definitions/json/EnglandWales Scrubbed.json
package.json

https://tools.hmcts.net/jira/browse/RET-1084
Merge ECM R5.0.24 
Remove duplicate rows in CaseTypeTab
```
[ ] Yes
[x] No
```

Merge ecm r5.0.24

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-879
Add initGenerateReport callback to populate Clerks
```
[ ] Yes
[x] No
```

Add initGenerateReport callback

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1189
Merge ECM R5.0.25
```
[ ] Yes
[x] No
```

Merge ECM R5.0.25

---

definitions/json/EnglandWales Scrubbed.json

added ecc report

---

definitions/json/EnglandWales Scrubbed.json

Ecm 553   added ecc report

---

definitions/json/CaseEventToFields.json
definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1436
ECM R5.0.26
```
[ ] Yes
[x] No
```

ECM R5.0.26

---

definitions/json/ComplexTypes.json

Revert BF Report field type changes
```
[ ] Yes
[x] No
```

Revert BF Report field type changes

---

definitions/json/CaseEventToFields.json

new mid event added

---

definitions/json/EnglandWales Scrubbed.json

Config changes required for ECM-664 added.
```
[ ] Yes
[X] No
```

config changes for ecm-664

---

definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-1463
Update CCD config to include sex and gender identity fields
```
[ ] Yes
[x] No
```

[RET-1463] Update CCD definitions: Sex and Gender identity

---

definitions/json/CaseTypeTab.json

table view added for hearingCollection

---

definitions/json/State.json

https://tools.hmcts.net/jira/browse/RET-1466
Remove "Draft" state in favour of "AWAITING_SUBMISSION_TO_HMCTS" state.
```
[ ] Yes
[x] No
```

RET-1466. Remove "Draft" state.

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-1983
Merge ECM R5.0.31
```
[ ] Yes
[x] No
```

Merge ECM R5.0.31

---

definitions/json/AuthorisationCaseField.json

(https://tools.hmcts.net/jira/browse/RET-1852)
```
[ ] Yes
[ x] No
```

Added missing permissions for demo

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json
definitions/json/EventToComplexTypes.json
definitions/json/SearchInputFields.json
definitions/json/WorkBasketInputFields.json
package.json
yarn.lock

Pi26 sprint 3

---

definitions/json/CaseEventToFields.json

Ret 2013 fix

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2040
```
[ ] Yes
[X] No
```

New midevent call back added

---

src/main/lib/substitutor.js

https://tools.hmcts.net/jira/browse/RET-1835
Fix failures on existing tests.
```
[ ] Yes
[x] No
```

Fix unit tests

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2024
Fixed permissions on 2024
```
[ ] Yes
[x] No
```

Ret 2024: Fix permissions on date labels

---

definitions/json/CaseEventToFields.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2067
Added extension fields to Respondent details
```
[ ] Yes
[x] No
```

RET-2067: Added Extension to respondentCollection complex type

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1982
Added 'Response in Time' Page for ET3 Vetting
```
[ ] Yes
[x] No
```

RET-1982: Added 'Response in Time' ET3 page

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1868
Add "referral to REJ / VP" page to the ET1 vetting event.
```
[ ] Yes
[x] No
```

RET-1868. Add "referral to REJ or VP" page to the ET1 vetting event.

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2015
```
[ ] Yes
[x] No
```

Ret 2015 auth for additional users 

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-1852
Fixes a strange behaviour of the multi select list.
```
[ ] Yes
[x ] No
```

RET-1852: Fixed strange behaviour of the multiselect field

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1846
Further questions page for vetting process.
```
[ ] Yes
[x] No
```

RET-1846. Further questions page.

---

definitions/json/CaseEvent.json

Temporary changes for testing ET1 vetting jurisdiction code

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1849
Add a post-vetting event page with next steps.
```
[ ] Yes
[x] No
```

RET-1849. Add post vetting event.

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2033
```
[ ] Yes
[X] No
```

RET-2033 - new field added

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

Fixed defects
https://tools.hmcts.net/jira/browse/RET-1842
```
[ ] Yes
[ x] No
```

Ret 1842 3

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2016
```
[ ] Yes
[x] No
```

Initial Consideration rule 26 page

---

definitions/json/AuthorisationCaseField.json

Fixed permissions for ET3 Vetting event
```
[ ] Yes
[X] No
```

Et3 permission tidy

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1845
Add suggest hearing venue page.
```
[ ] Yes
[x] No
```

Ret 1845. Add suggest hearing venue page.

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2017
Display initial consideration fields in check your answers page
```
[ ] Yes
[x] No
```

RET-2017: Enable initial consideration fields in check your answers page

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2117
Remove New employment details from Create Case event
```
[ ] Yes
[x] No
```

RET2117: Remove New employment details from Create Case event

---

definitions/json/CaseEvent.json

Change label to Processing
```
[ ] Yes
[X] No
```

Change label to Processing

---

definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-2151
Ret 2151. Hide et1 vetting tab when not yet vetted.
```
[ ] Yes
[x] No
```

Ret 2151. Hide et1 vetting tab when not yet vetted.

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2160
```
[ ] Yes
[X] No
```

Ret 2160 new

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2161
```
[ ] Yes
[x ] No
```

RET-2161: Show Send Documents and Send to Acas pages

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1903
https://tools.hmcts.net/jira/browse/RET-1904
https://tools.hmcts.net/jira/browse/RET-1908
https://tools.hmcts.net/jira/browse/RET-1909
Added pages 1903, 1904, 1908 and 1909
```
[ ] Yes
[x] No
```

Added up to RET-1909

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1910
https://tools.hmcts.net/jira/browse/RET-1911
https://tools.hmcts.net/jira/browse/RET-1912
https://tools.hmcts.net/jira/browse/RET-1914
https://tools.hmcts.net/jira/browse/RET-1915
Added 1910, 1911, 1912, 1914 and 1915
```
[ ] Yes
[x] No
```

Added up to 1915

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

Changed YesOrNo to fixed radio list for claimant job details
```
[ ] Yes
[x] No
```

Changed YesOrNo to fixed radio list for claimant job details

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1882
Added regex to phone number
```
[ ] Yes
[X] No
```

RET-1882-Fix: Added regex to the phone number

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2059
Fixed permissions for field
```
[ ] Yes
[X] No
```

RET-2059 Fix

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

Change caseworker-ET-pcqextractor role to be lowercase so that it is consistent with all other roles
```
[ ] Yes
[x] No
```

Fix case of caseworker-ET-pcqextractor role

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

Merge update caseworker-ET-pcqextractor role
```
[ ] Yes
[x] No
```

Merge update caseworker-ET-pcqextractor role

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2216
Removed superfluous 'y' on case field
```
[ ] Yes
[x] No
```

Removed superfluous 'y' on case field

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2221
Fixed issues not showing in CYA
```
[ ] Yes
[x] No
```

fixes issues not showing in CYA

---

definitions/json/CaseEvent.json

RET-2238: ET1 case vetting now available on states: Rejected;Vetted

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

RET-2220, 2221
```
[ ] Yes
[X] No
```

EngWales Patch

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2201
https://tools.hmcts.net/jira/browse/RET-2205
New fields and callback for ET1 Vetting and ET3 Processing PDF
```
[ ] Yes
[X] No
```

RET-2201/5

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2260
Add Hublinks to the update draft case event and to the CCD config.
```
[ ] Yes
[x] No
```

RET-2260. Add hublinks complex field.

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2411
Add support for et3Response document generation
```
[ ] Yes
[x] No
```

Add support for et3Response document generation

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1454
Added callback URLs to SUBMIT_CASE_DRAFT in CaseEvent.json on lines 43 & 44.
```
[ ] Yes
[X] No
```

RET-1454 Handle logic upon case submission

---

definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-1937
Adding necessary fields
```
[ ] Yes
[x] No
```

Ret 1937 - Claim Details

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json

https://tools.hmcts.net/jira/browse/RET-2528
Removed ACAS role from certain case states and fields
```
[ ] Yes
[X] No
```

Modified ACAS permissions

---

definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2072
```
[ ] Yes
[x ] No
```

RET-2072: Adding new Rejection of Claim field to Upload Document event

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
package.json

https://tools.hmcts.net/jira/browse/RET-2538
Allow a submitted case's details to be updated.
```
[ ] Yes
[x] No
```

RET-2538. Add event to update a submitted case's data.

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/CaseEventToFields.json

Added fields for SUBMITTED case update

---

definitions/json/AuthorisationCaseField.json

Removed additional documents which ACAS could see
```
[ ] Yes
[ ] No
```

Acas permissions

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2578
Bug fixes from final checks testing
Invalid date error message not displaying
Show ethosCaseReference for submitted claims
```
[ ] Yes
[ x] No
```

RET-2578: Add complexType 'other_claim'

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2603
```
[ ] Yes
[x] No
```

Ret 2603 - Document alerts not appearing on citizen hub

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2612
added aboutToSubmit callback for uploadDocument
```
[ ] Yes
[x] No
```

RET-2612: Email on case rejection document upload

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1856
added callback for et1Serving submitted
```
[ ] Yes
[x] No
```

RET-1856: added callback for et1Serving submitted

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2639
Add pdf to complex types
```
[ ] Yes
[X] No
```

2639: add pdf to complex types

---

definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2273
Added Tribunal case file to fl_DocumentType
```
[] Yes
[x] No
```

RET-2273: CR: Add Tribunal case file to fl_DocumentType

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2323
CR: Add validation to the disposal date field at jurisdiction level
```
[] Yes
[x] No
```

RET-2323: CR: Add validation to the disposal date field at jurisdiction level

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2684
Changed Initial Consideration Before You Start label text
```
[] Yes
[x] No
```

RET-2684: Changed Initial Consideration Before You Start label text

---

definitions/json/EnglandWales Scrubbed.json

Code changes to implement ret-2592, i.e. added fixed list items for letter templates.
https://tools.hmcts.net/jira/browse/RET-2592
```
[ ] Yes
[X] No
```

ret-2592 implementation

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2063
ET3 Notification complete
```
[ ] Yes
[x] No
```

RET-2063: ET3 Notification complete

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-2590
Add a suggested hearing venue field to the case details tab
```
[] Yes
[x] No
```

RET-2590: Add a suggested hearing venue field to the case details tab

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/WorkBasketInputFields.json
definitions/json/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/RET-2275
```
[ ] Yes
[ X ] No
```

ret-2275 implementation

---

definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2796
Added Vacated option
```
[ ] Yes
[X] No
```

RET-2796 Added Vacated option

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2839
```
[ ] Yes
[X] No
```

ACAS email address corrected

---

definitions/json/AuthorisationCaseEvent.json

Revert shutter ET3 form and ET3 notification

---

definitions/json/AuthorisationCaseEvent.json

Small fix to add api user role to new nocRequest event
```
[ ] Yes
[ x ] No
```

Added api role to nocRequest event

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3047
Fixed Authorisations for ET3 Response Form
```
[] Yes
[x] No
```

RET-3047: Fixed Authorisations for ET3 Response Form

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2772-post-reply-merge
Added fields to reflect post reply merge, replicated tseAdmReply to Scotland
```
[] Yes
[x] No
```

RET-2772-post-reply-merge: Added fields to reflect post reply merge, replicated tseAdmReply to Scotland

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

2772 update roles

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2617
Renaming fields to match frontend, api, data model.
```
[ ] Yes
[X] No
```

RET-2617 - Renaming rule 92 fields

---

definitions/json/EnglandWales Scrubbed.json

Pet 1.1.0.6

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2949
Deleted additional letter question from send notification
```
[] Yes
[x] No
```

RET-2949: Deleted additional letter question from send notification

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2949
Fixed Full Name under Case Management Orders / Request
```
[] Yes
[x] No
```

RET-2949: Fixed Full Name under Case Management Orders / Request

---

definitions/json/AuthorisationCaseField.json

Added missing role for TSE doc upload 2

---

definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3206
```
[ ] Yes
[X] No
```

Ret 3206 new

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3174
```
[ ] Yes
[x ] No
```

RET-3174 added read permissions for et-acas-api

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3116
https://tools.hmcts.net/jira/browse/RET-3117
```
[ ] Yes
[X] No
```

RET-3116-3117 date format

---

definitions/json/CaseField.json

revert field data type

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3026
```
[ ] Yes
[X] No
```

RET-3026 add about to start

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2953
```
[ ] Yes
[ x] No
```

RET-2953 added respond to a notification

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3048
View all Judgement, Orders and Notification
```
[] Yes
[x] No
```

RET-3048: View all Judgement, Orders and Notification

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3244
Add application state
```
[ ] Yes
[x] No
```

RET-3244 - Add application state

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2949
Various fixes for 2949
```
[] Yes
[x] No
```

RET-2949: Various fixes for 2949

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3250
Hide application state
```
[ ] Yes
[x] No
```

Hide application state

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2896
```
[ ] Yes
[X] No
```

RET 2896 view application

---

definitions/json/CaseEvent.json

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RET-3314
Change description
Added Response Complete functionality
Does this PR introduce a breaking change? (check one with "x")

RET-3314: Add Close Application Submit

---

package.json

Updated preview links

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-3333
```
[ ] Yes
[x] No
```

RET-3333 Send notification - upload mandatory when add doc is selected

---

definitions/json/CaseEventToFields.json

RET-3332: Fix for field not appearing

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2948
Added notifications tab
```
[] Yes
[x] No
```

RET-2948: Added notifications tab

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2956
```
[ ] Yes
[x ] No
```

Ret 2956 Provide something Tribunal asked for - Respond to a notification (ECM) - notify selected parties (email) 

---

definitions/json/AuthorisationCaseField.json

Ret 2982 new field access

---

definitions/json/EnglandWales Scrubbed.json

RET-3347 master

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3106
Added page 3 of Bundles Respondent journey
```
[] Yes
[x] No
```

RET-3106: Added page 3 of Bundles Respondent journey

---

package.json

N/A
Update preview link for Release 2.0
```
[ ] Yes
[x] No
```

Update preview link for Release 2.0

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2929
```
[ ] Yes
[x ] No
```

RET-2929 Provide something Tribunal asked for - CYA page for response to order/request from Tribunal (CitizenUI)

---

definitions/json/CaseEvent.json

RET-3438: Fix for NOC email is not being sent to Removed Organisation

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3233
Adding decision state to admin decision.
```
[ ] Yes
[X] No
```

Ret 3233 - View an application/case judgment from CitizenUI hub page

---

definitions/json/ComplexTypes.json

Fix Field not recognised on Respond to Notification
```
[] Yes
[x] No
```

RET-0000: Fix Field not recognised on Respond to Notification

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2435
```
[ ] Yes
[ x] No
```

Ret 2435 Create "IssueInitialConsiderationDirections" Task for Admin

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RET-2347
Publish Event and Fields needed for Work Allocation
```
[ ] Yes
[x] No
```

Ret 2347 - Create Task "ReviewReferralAdmin" for Admin

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2379
https://tools.hmcts.net/jira/browse/RET-2380
https://tools.hmcts.net/jira/browse/RET-2381
This story deals with the automated creation of "ReviewReferralResponseAdmin" task following a referral event
```
[ ] Yes
[x] No
```

RET-2379-ReviewReferralResponseAdmin

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2373
https://tools.hmcts.net/jira/browse/RET-2374
https://tools.hmcts.net/jira/browse/RET-2375
```
[ ] Yes
[x ] No
```

RET-2373 add ListServeClaim

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2444
https://tools.hmcts.net/jira/browse/RET-2445
https://tools.hmcts.net/jira/browse/RET-2446
Create "DraftAndSignJudgment" Task for Judge
```
[ ] Yes
[x] No
```

RET-2444: Create "DraftAndSignJudgment" Task for Judge

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3662
Revert to plain text.
```
[ ] Yes
[ ] No
```

RET-3662 - Fix Broken Link

---

definitions/json/CaseField.json

Reverts hmcts/et-ccd-definitions-englandwales#505

Revert "RET-3662 - Fix Broken Link"

---

definitions/json/ComplexTypes.json

Show address field without needing to answer MyHMCTS question
```
[ ] Yes
[ ] No
```

Show address field

---

definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3760
make field optional
```
[ ] Yes
[x] No
```

RET-3760 - Change short description for et3 notif

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3761
Altered ServingDocumentUpload event to make shortDescription optional
```
[ ] Yes
[x] No
```

RET-3761 short description for serving doc

---

definitions/json/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2658
RET-2658: Give role access to task
```
[ ] Yes
[x] No
```

RET-2658: Give role access to task

---

definitions/json/CaseEventToFields.json

Fix import error

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

https://tools.hmcts.net/jira/browse/RET-2658
[RET-2658: Give role access to event/state/type](https://github.com/hmcts/et-ccd-definitions-englandwales/commit/19312adc02271d86684b9791c406fab5fd7e3c13)
```
[ ] Yes
[x] No
```

RET-2658: Give role access to event/state/type

---

definitions/json/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-3720
RET-3720: Add RoleToAccessProfiles.json
```
[ ] Yes
[x] No
```

RET-3720: Add RoleToAccessProfiles.json

---

env.json

RET-3720: Return Preview links

---

definitions/json/CaseEvent.json
env.json

https://tools.hmcts.net/jira/browse/RET-3684
Make it easier to search based on the title in ExUI
```
[ ] Yes
[x] No
```

Update event name and description for easier search

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3720
Add authorisations to CaseFields
```
[ ] Yes
[x] No
```

RET-3720: Add Authorisation

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3720
Authorise fields used in Conf DMN
```
[ ] Yes
[x] No
```

RET-3720: Authorisation to CaseData fields

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2515
Add HMCTSServiceId supplementary_data to cases
```
[] Yes
[x] No
```

RET-2515: Add HMCTSServiceId supplementary_data to cases

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3188
https://tools.hmcts.net/jira/browse/RET-3189
https://tools.hmcts.net/jira/browse/RET-3190
```
[ ] Yes
[ ] No
```

publish id updated

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-3246
```
[ ] Yes
[x ] No
```

RET-3246 Make an application CYA - Check your answers page has no application type

---

definitions/json/ComplexTypes.json

RET-3794: Relocated response required fields

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3667
Adjusted permissions on CaseFlags related fields/events
```
[] Yes
[x] No
```

RET-3667: Adjusted permissions on CaseFlags related fields/events

---

definitions/json/CaseField.json

RET-3794: set character limit to fields

---

definitions/json/CaseEvent.json

Revert changes in RET-2919
```
[ ] Yes
[x] No
```

PET-1.1.2.2 (Revert)

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3767
Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag
```
[] Yes
[x] No
```

RET-3767: Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3663
```
[ ] Yes
[x] No
```

RET-3663 - Remove notifications tab for Legal Rep

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

N/A
Fix merge conflicts
```
[ ] Yes
[x] No

2.0 mergeconflicts

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3766
Added publicCaseName to CaseField.json and AuthorisationCaseField.json
```
[ ] Yes
[X] No
```

RET-3766 : Determine public case name for hearing request

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3792
Add viewedByClaimant property
```
[ ] Yes
[x] No
```

RET-3792 - Add viewedByClaimant property

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2501
Quick Fix for Typo
```
[ ] Yes
[x] No
```

RET-2501- fix publish

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3810
```
[ ] Yes
[x] No
```

RET-3810: Add field for caseDeepLink

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3857
Add private hearing question as part of initial consideration, made changes to CaseFields.json, CaseEventToField.json and AuthorisationCaseField.json
```
[ ] Yes
[X] No
```

RET-3857: Add private hearing question as part of initial consideration

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4044
Rename caseNameHmctsInternal
```
[x] Yes
[ ] No
```

RET-4044 - Rename caseNameHmctsInternal

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3602
Modify caseworker access
```
[ ] Yes
[x] No
```

RET-3602 - Modify caseworker access

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationComplexType.json

https://tools.hmcts.net/jira/browse/RET-4013
-----
Permission updates to legalrep/solicitor
-----
```
[ ] Yes
[X] No
```

RET-4013 Permission updates to legalrep/solicitor

---

definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json
definitions/json/RoleToAccessProfiles.json

n/a
For QA
```
[ ] Yes
[x] No
```

Add caseworker-ras-validation

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4096
```
[ ] Yes
[ ] No
```

RET-4096 cancelTask changes

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2370
https://tools.hmcts.net/jira/browse/RET-2373
Fix Typo
```
[ ] Yes
[x] No
```

RET-2370: Fix Typo

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3820
https://tools.hmcts.net/jira/browse/RET-4081
Send case linking email
```
[ ] Yes
[x] No
```

RET-3820 + RET-4081 - Add callback to send case linking emails

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3842
```
[ ] Yes
[x] No
```

RET 3842 Add hearingIsLinkedFlag

---

definitions/json/EnglandWales Scrubbed.json
definitions/json/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/RET-4042
https://tools.hmcts.net/jira/browse/RET-4117
```
[ ] Yes
[X] No
```

RET-4042, 4117

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4095
Add Publish to Events in Completion DMN
```
[ ] Yes
[x] No
```

RET-4095: Publish Complete Events

---

definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-3910
```
[ ] Yes
[X] No
```

RET-3910 - tab order change

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4095
Add more Completion events
```
[ ] Yes
[x] No
```

RET-4095: Publish Completion Events

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3514
Allow Non System Users Respond to an Application
```
[ ] Yes
[X] No
```

RET-3514 Allow Non System Users Respond to an Application

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4169
https://tools.hmcts.net/jira/browse/RET-4170
Added new event for ACAS Cert lookup
Added ACAS Cert regex to fields
Made feeGroupReference optional
```
[ ] Yes
[X] No
```

RET-4169, RET-4170

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3607
Add read permission to legal rep
```
[ ] Yes
[x] No
```

RET-3607 - Add read permission to legal rep

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4019
Add missing tab
```
[ ] Yes
[x] No
```

RET-4019 add hearing unavailability tab

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4122
```
[ ] Yes
[x] No
```

RET-4122 add caseManagementLocationCode

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4021
RET-4021: Display notification banner on tribunal notification responses
```
[] Yes
[x] No
```

RET-4021: Display notification banner on tribunal notification responses

---

definitions/json/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3891
added fl_DocumentType, Tse admin correspondence to englandwales scrubbed json file
```
[ ] Yes
[X] No

RET-3891 Tribunal Respond to Application Create PDF file 

---

definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4228
Renaming legacy hearings tab
```
[] Yes
[x] No
```

RET-4228: Renaming legacy hearings tab

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4024
Add permission for judges
```
[ ] Yes
[x] No
```

RET-4024 - Add permission for judges

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEvent.json
definitions/json/ComplexTypes.json

Merge new event to master/aat
Note - only used in Rule 92 and won't be called in Prod yet

Ret 4062 event

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4158
Add Authorisation for WA to CML and CMC fields

RET-4158: Add Authorisation for WA to CML and CMC fields

---

definitions/json/RoleToAccessProfiles.json

Fix ES Creator issue

---

definitions/json/CaseEvent/CaseEvent.json

FixCase vetted state

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4062
CUI side of the Rule 92 for non system user
Add status in tseReply and pseRespondCollection

RET-4062 - Add tseReply storedPending

---

definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4004
Permissions for data needed for Work Allocation.
Referral/Application Replies

RET-4004 WA enablers

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-CaseFlagsCaseLinking-nonprod.json
definitions/json/CaseEvent/CaseEvent-CaseFlagsCaseLinking-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4295
Add migration events for case flags

RET-4295 - Add migration events

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4004
Added missing Publish

RET-4004: ReferralFix

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4378

RET-4378 Bug - allow legal rep to create application

---

definitions/json/CaseEvent/CaseEvent-HMC-nonprod.json
definitions/json/CaseEvent/CaseEvent-prod.json
definitions/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4382
Add callback to addAmendClaimantRepresentative for HMC
```
[] Yes
[x] No
```

RET-4382: Add callback to addAmendClaimantRepresentative for HMC

---

definitions/json/ComplexTypes/ComplexTypes-Bundles.json

https://tools.hmcts.net/jira/browse/RET-3082

RET-3082 rename field

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-HMC-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseEvent/CaseEvent-HMC-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-HMC-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json

Party unavailability dates (HMC)
```
[] Yes
[x] No
```

RET-0000: Party unavailability dates (HMC)

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json
env.json

https://tools.hmcts.net/jira/browse/RET-4016
Added issueInitialConsiderationDirectionsWA event
```
[] Yes
[x] No
```

RET-4016: Added issueInitialConsiderationDirectionsWA event

---

definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-4014
Publish CaseData

RET-4014: Publish caseData

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField.json
definitions/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4192
Ensure fields for old flow of InitialConsideration continue to exist

RET-4192: Restore old caseFields

---

package.json
yarn.lock

Revert matcher

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4507
Add create lead case event

RET-4507 - Add lead case event

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-3296
Additional Authorisation

RET-3296: Add Authorisation

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-prod.json
definitions/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4516
Change triggering event for Et3Processing

RET-4516: Change triggering event for Et3Processing

---

definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-prod.json
definitions/json/CaseEventToFields/CaseEventToFields.json

###Making referentEmail,updateReferentEmail,replyToEmailAddress optional ###
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)

merging RET-4513-referentEmail-updateReferentEmail-replyToEmailAddress

---

definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-4346
ECC- Extra radio button to be added to What is the ECC notification

RET-4346 - Add ECC radio button

---

definitions/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4344
Update hint text

RET-4344-Update hint text

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

Added nested complexType field in EventToComplexType

Added nested complexType field in EventToComplexType

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json

Added missing HMC fields from Release-2.2 branch
```
[] Yes
[x] No
```

RET-0000: Added missing HMC fields from Release-2.2 branch

---

definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4393
Add responseState to pseRespondCollection

RET-4393 - PSE- Display response from claimant

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json
definitions/json/CaseField/CaseField-WA-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-WA-nonprod.json

###(https://tools.hmcts.net/jira/browse/RET-3991)
- [x ] README and other documentation has been updated / added (if needed)

adding icListingPreliminaryHearing

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json

fix duplicate IC field
```
[] Yes
[x] No
```

RET-0000: fix duplicate IC field

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4643
Added permissions for legalrep-solicitor for nextListedDate
```
[] Yes
[x] No
```

RET-4643: Added permissions for legalrep-solicitor for nextListedDate

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Bundles-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

Formatted JSON files
```
[] Yes
[x] No
```

RET-0000: Formatted JSON files

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4611
Added Docs, Claimant Docs and Respondent Docs for Multiples
```
[] Yes
[x] No
```

RET-4611: Added Docs, Claimant Docs and Respondent Docs for Multiples

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json

https://tools.hmcts.net/jira/browse/COT-708
https://tools.hmcts.net/jira/browse/COT-731
RAS Validation is missing access to the Case Region

COT-708-731: Give RAS access to Case Region

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-prod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-4676
Add missing SA and CA, also update access profiles

RET-4676: Add missing SA and CA, also update access profiles

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-prod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-4681
Removed some Idam mapping as was granting Users with this role Standard Access to cases

RET-4681: Remove global Standard Access roles

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4700
Add applications tab

RET-4700 - Add applications tab

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/CaseField/CaseField-WA-nonprod.json
definitions/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4677
Give WA access to Category

RET-4677: Give WA access to Category

---

definitions/json/ComplexTypes/ComplexTypes.json

Remove short desc show condition

---

definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4748
Make further info optional

RET-4748 - Make further info optional

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-WA-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json
definitions/json/CaseField/CaseField-WA-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-WA-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-prod.json
definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4740
Create DraftAndSignJudgement event

RET-4740 - Create DraftAndSignJudgement event

---

definitions/json/CaseEvent/CaseEvent-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-prod.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4718
Publishing caseTransferSameCountry event
```
[] Yes
[x] No
```

RET-4718: Publishing caseTransferSameCountry event

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4699
Enable upload document

RET-4699-V2-Enable upload document

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4741
Remove legal rep access and add caseworker

RET-4741 - Remove legal rep access and add caseworker

---

definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-prod.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4784
Publish hearingDetailsStatus

RET-4784 - Publish hearingDetailsStatus

---

definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4752
Publish isJudgement for WA

RET-4752: Publish isJudgement for WA

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4741
Update LegalOps access to include Judges Tasks

RET-4741: Update for LegalOps to do Judge Task

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4250
Add Case Stayed option to batch update
```
[] Yes
[x] No
```

RET-4250: Add Case Stayed option to batch update

---

definitions/json/ComplexTypes/ComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4864
Hide WA Only Internal Fields from EXUI

RET-4864: Hide WA Only Internal Fields from EXUI

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4687
Rename controller route

RET-4687 - Rename controller route

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4699
update Callbacks URL to the new multiples endpoint for the upload document event

RET-4699-updateCallbacksURL

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4743
Add notificationSentFrom

RET-4743 - Add notificationSentFrom

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4704
Copy updateReferral to _Multiples case types
```
[] Yes
[x] No
```

RET-4704: Copy updateReferral to _Multiples case types

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4706
Add close referral to multiple

RET-4706 - Add close referral to multiple

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4704
Update ReplyToReferral and UpdateReferral
```
[] Yes
[x] No
```

RET-4704: Update ReplyToReferral and UpdateReferral

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4715
Batch send notifications

RET-4715 - Add batch processing to send notification

---

definitions/json/ComplexTypes/ComplexTypes-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json

https://tools.hmcts.net/jira/browse/RET-4926
Add a counter so that the ET3 Processing Task would only trigger once.

RET-4926: New Counter for WA Task

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA.json
definitions/json/CaseEvent/CaseEvent-WA.json

https://tools.hmcts.net/jira/browse/RET-5020
https://tools.hmcts.net/jira/browse/RET-5026
- Added Rejected as a precondition state for amendRespondentDetails
- Add extra permissions for draftAndSignJudgment event

RET-5020 and 5026

---

definitions/json/ComplexTypes/ComplexTypes.json

[(https://tools.hmcts.net/jira/browse/RET-4977)]
Config change to display hearing number selection during the letter generation for 15.4 and 15.6.

doc 15.4 and 15.6 hearing display update

---

definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-5037
Remove dependancy on CMO being selected for showing response required and select parties fields
```
[] Yes
[x] No
```

RET-5037: Remove dependancy on CMO being selected for showing response required and select parties fields

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/CaseField/CaseField-WA.json

Add CaseManagementLocationCode to WA

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4732
Add notifications extract

RET-4732 - Add notifications extract

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/Categories/Categories.json

https://tools.hmcts.net/jira/browse/RET-4617
CaseFileView for Multiples
```
[] Yes
[x] No
```

RET-4617: CaseFileView for Multiples

---

definitions/json/EventToComplexTypes/EventToComplexTypes-ECC-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5038
Publish et3ContractClaimSection7

RET-5038 - Publish et3ContractClaimSection7

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-Multiples-nonprod.json
yarn.lock

https://tools.hmcts.net/jira/browse/RET-5053
Add case note feature

Ret 5053 - Add case note feature

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5064
Add DCF to multiple

RET-5064 - Add DCF to multiple

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-5181
case field authorisation updated for legal rep
- [x ] commit messages are meaningful and follow good commit message guidelines

legal rep authorisation updated

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5196
Change text of button for Referral Events

RET-5196: Change text of button for Referral Events

---

definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-5206
Add author

RET-5206 - Add author

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed-Multiples-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-5205
RET-5205: Remove sub-case from Multiple with using Batch Process

RET-5205: Remove Subcase from Multiple

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5205
Authorisation CaseField

RET-5205: Authorisation CaseField

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-prod.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5258
Update based on testing

RET-5258: Update Authorisation and AdditionalFields

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5258
All WA to see MultipleName

RET-5258: Allow WA Access to Multiple name

---

definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5232
Fix for DynamicListCollection
```
[] Yes
[x] No
```

RET-5232: Fix for DynamicListCollection

---

definitions/json/CaseTypeTab/CaseTypeTab.json

Hide Notification tab until RET-5309 and related tickets are completed

Hide Notification tab until RET-5309 and related tickets are completed

---

definitions/json/ComplexTypes/ComplexTypes.json

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Restore old field for payload

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-ET1Repped.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEvent/CaseEvent-WA.json
definitions/json/CaseEventToFields/CaseEventToFields-WA.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

claimant responding logic

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEventToFields/CaseEventToFields-WA.json
definitions/json/CaseField/CaseField.json
definitions/json/ComplexTypes/ComplexTypes-ET3-nonprod.json
definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-5437
Respondent hearing panel reference fields added
- [ x] commit messages are meaningful and follow good commit message guidelines

ret-5437 implementation

---

definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed.json

See [RET-5637](https://tools.hmcts.net/jira/browse/RET-5637)
Added new letter part

Add new letter into part 13

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json

https://tools.hmcts.net/jira/browse/RET-5733
Added WA permissions to fields

Add WA permissions to fields

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

See [RET-5736](https://tools.hmcts.net/jira/browse/RET-5736)
Make document types mandatory when adding a document

RET-5736 - When adding a doc, doc types are mandatory

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseField/CaseField.json

See [RET-5764](https://tools.hmcts.net/jira/browse/RET-5764)
Added new field for ACAS Cert Cron Job

Add new ACAS doc field

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-5628
Casedata fields published to be used as input for setting the draft and sign judgment due date.
- [ x ] commit messages are meaningful and follow good commit message guidelines

draft and sign judgment due date input published

---

definitions/json/ComplexTypes/ComplexTypes.json

See [RET-5807](https://tools.hmcts.net/jira/browse/REt-5807)
Added new case flag

Added new case flag

---

definitions/json/ComplexTypes/ComplexTypes-ET3.json

See [RET-5841](https://tools.hmcts.net/jira/browse/RET-5841)
Add dummy show condition to hide field

Hide Respondent IDAM ID

---

definitions/json/EnglandWales Scrubbed/EnglandWales Scrubbed.json

See [RET-5887](https://tools.hmcts.net/jira/browse/RET-5887)
Added new letter option

Update display order for response options in EnglandWales Scrubbed.json

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json

See [RET-5933](https://tools.hmcts.net/jira/browse/RET-5933)
See [RET-5934](https://tools.hmcts.net/jira/browse/RET-5934)
See [RET-5935](https://tools.hmcts.net/jira/browse/RET-5935)
Give WA permission to view ethosCaseReference to allow it to be used in caseName (see https://github.com/hmcts/et-wa-task-configuration/pull/386)

RET-5933-35

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-WA.json

https://tools.hmcts.net/jira/browse/RET-5796
Initial Consideration related documents links added

ic doc links added

---

definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes-ET3.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-6022
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Field added on the respondent details event and respondents tab

RET-6022 - add field for ECC Reply
